api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views as vs
from . import views

app_name='api'

router=DefaultRouter()
router.register('products',views.ProductViewsets)
router.register('categories',views.CategoryViewsets)
router.register('reviews',views.ReviewViewsets)
router.register('offers',views.OfferViewsets)
router.register('cart',views.CartViewsets)
router.register('coupon',views.CouponViewsets)
router.register('order',views.OrderViewsets)
router.register('order_products',views.OrderProductViewsets)
router.register('users',views.UserViewsets)

urlpatterns = [
    path('',include(router.urls)),
    path('api-token-auth/', vs.obtain_auth_token),
]

cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('',views.cart,name='cart'),
    path('remove_cart/<int:item_id>',views.remove_cart,name='remove_cart'),
    path('add_cart/<int:product_id>',views.add_cart,name='add_cart'),
    path('add_item/<int:item_id>',views.add_item,name='add_item'),
    path('remove_item/<int:item_id>',views.remove_item,name='remove_item'),
]

order/urls.py
from django.urls import path
from . import views

app_name='order'

urlpatterns = [
    path('',views.orders,name='orders'),
    path('checkout/<int:subTotal>/<int:shipping>',views.checkout,name='checkout'),
    path('cancel/<int:order_id>',views.cancel_order,name='cancel'),
    path('approve/<int:order_id>',views.approve_order,name='approve'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('shop/',include('shop.urls',namespace='shop')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('order/',include('order.urls',namespace='order')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('api/',include('api.urls',namespace='api')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns = [
    path('',views.shop,name='shop'),
    path('price',views.shop_price,name='shop_price'),
    path('cats/<str:cat_name>/',views.shop_cats,name='shop_cats'),
    path('product_details/<str:product_name>',views.product_details,name='product_details'),
    path('search',views.search,name='search'),
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import Product

# Create your models here.
class Cart(models.Model):
    user=models.ForeignKey(User, verbose_name=("User"), on_delete=models.CASCADE,null=True)
    product=models.ForeignKey(Product, verbose_name=("Product"), on_delete=models.CASCADE)
    quantity=models.IntegerField(verbose_name=("Quantity"))
    price=models.IntegerField(verbose_name=("Price"),null=True,blank=True,)
    total=models.IntegerField(verbose_name=("Total"),null=True,blank=True)
    
    class Meta:
        verbose_name = ("Cart")
        verbose_name_plural = ("Carts")
        
    def save(self,*args,**kwargs):
        if self.quantity > self.product.stock:
            self.quantity=self.product.stock
        if self.product.offer_price:
            self.price=self.product.offer_price
        else:
            self.price=self.product.price
        self.total=self.quantity*self.price
        super(Cart,self).save(*args, **kwargs)

    def __str__(self):
        return str(self.product)

class Coupon(models.Model):
    coupon=models.CharField(verbose_name=("Coupon"),max_length=50)
    ratio=models.IntegerField(verbose_name=("Ratio"))
    created_at=models.DateField(verbose_name=("Created at"), auto_now=True)
    expiry_date=models.DateField(verbose_name=("Expires at"),null=True)
    is_available=models.BooleanField(verbose_name=("Is Available"),default=True)

    class Meta:
        verbose_name = ("Coupon")
        verbose_name_plural = ("Coupons")
        
    def save(self,*args,**kwargs):
        self.coupon=str(self.coupon).upper()
        super(Coupon,self).save(*args, **kwargs)

    def __str__(self):
        return str(self.coupon).upper()

cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .models import *

# Create your views here.
@login_required(login_url='accounts:login_view')
def cart(request,subTotal=0,shipping=50,grandTotal=0,discount=0,originalTotal=0):
    try:
        try:
            cartItem=Cart.objects.all().filter(user=request.user)
            for item in cartItem:
                subTotal+=item.total
        except:
            cartItem=None
        if request.method=='POST':
            
            discount=request.POST['coupon']
            if discount:
                try:
                    coupon=Coupon.objects.get(coupon=str(discount))
                    grandTotal=subTotal+shipping
                    originalTotal=grandTotal
                    discount=grandTotal*(coupon.ratio/100)
                    grandTotal=int(grandTotal-discount)
                except:
                    pass
        else:
            shipping=50
            grandTotal=subTotal+shipping
    except:
        pass
    context={
        'subTotal':subTotal,
        'grandTotal':grandTotal,
        'shipping':shipping,
        'discount':discount,
        'originalTotal':originalTotal,
        'cartItem':cartItem,
    }
    
    return render(request,'cart/cart.html',context)

def remove_cart(request,item_id):
    
    cartItem=Cart.objects.get(id=item_id)
    cartItem.delete()
    
    return redirect('cart:cart')

def add_item(request,item_id):
    cartItem=Cart.objects.get(id=item_id)
    cartItem.quantity+=1
    cartItem.save()
    
    return redirect('cart:cart')

def remove_item(request,item_id):
    cartItem=Cart.objects.get(id=item_id)
    if cartItem.quantity>1:
        cartItem.quantity-=1
        cartItem.save()
    else:
        cartItem.delete()
    return redirect('cart:cart')

@login_required(login_url='accounts:login_view')
def add_cart(request,product_id,cartItem=None):
    product=Product.objects.get(id=product_id)
    
    try:
        cartItem=Cart.objects.get(user=request.user,product=product)
    except:pass
    if cartItem:
        cartItem.quantity+=1
        cartItem.save()
    else:
        if request.method=='POST':
            amount=int(request.POST["quantity"])
            if amount:
                cartItem=Cart(user=request.user,product=product,quantity=amount)
                cartItem.save()
        else:
            return redirect("cart:product_details")
    return redirect("cart:cart")

templates/cart/cart.html
{% extends "base.html" %}

{% block content %}

        <!-- Cart Page Start -->
        <div class="container-fluid py-5 mt-5">
            <div class="container py-5">
                <div class="table-responsive">
                    {% if cartItem %}
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">Products</th>
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total</th>
                            <th scope="col">Handle</th>
                          </tr>
                        </thead>
                        
                        {% if cartItem %}
                        {% for item in cartItem %}
                        <tbody>
                            <tr>
                                <th scope="row">
                                    <div class="d-flex align-items-center">
                                        <img src="{{item.product.images.url}}" class="img-fluid me-5 rounded-circle" style="width: 80px; height: 80px;" alt="">
                                    </div>
                                </th>
                                <td>
                                    <p class="mb-0 mt-4">{{item}}</p>
                                </td>
                                <td>
                                    <p class="mb-0 mt-4">{{item.price}} $</p>
                                </td>
                                <td>
                                    <div class="input-group quantity mt-4" style="width: 100px;">
                                        <div class="input-group-btn">
                                            <a href="{% url "cart:remove_item" item.id %}">
                                                <button class="btn btn-sm btn-minus rounded-circle bg-light border" >
                                                    <i class="fa fa-minus"></i>
                                                </button>
                                            </a>
                                        </div>
                                        <div class="form-control form-control-sm text-center border-0 bg-transparent">{{item.quantity}}</div>
                                        <div class="input-group-btn">
                                            {% if item.quantity != item.product.stock %}
                                            <a href="{% url "cart:add_item" item.id %}">
                                                <button class="btn btn-sm btn-minus rounded-circle bg-light border" >
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            </a>
                                            {% endif %}
                                        </div>

                                        
                                    </div>
                                </td>
                                <td>
                                    <p class="mb-0 mt-4">{{item.total}} $</p>
                                </td>
                                <td>
                                    <a href="{% url "cart:remove_cart" item.id %}">
                                        <button class="btn btn-md rounded-circle bg-light border mt-4" >
                                            <i class="fa fa-times text-danger"></i>
                                        </button>
                                    </a>
                                </td>
                            
                            </tr>
                            {% endfor %}
                        {% endif %}
                            {% else %}
                            <div class="py-4 mb-4 border-top border-bottom d-flex justify-content-center">
                                <h2 class="mb-0 ps-4 me-4">No Items</h2>
                                <a href="{% url "shop:shop" %}">
                                    <button class="btn btn-md  bg-light border" >
                                        Add Item
                                    </button>
                                </a>
                            </div>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
                <div class="mt-5">
                    <form action="{% url "cart:cart" %}" method="POST">
                        {% csrf_token %}
                        <input type="text" class="border-0 border-bottom rounded me-5 py-3 mb-4" placeholder="Coupon Code" name='coupon'>
                        <input class="btn border-secondary rounded-pill px-4 py-3 text-primary" type="submit" value="Apply Coupon">
                    </form>
                </div>
                <div class="row g-4 justify-content-end">
                    <div class="col-8"></div>
                    <div class="col-sm-8 col-md-7 col-lg-6 col-xl-4">
                        <div class="bg-light rounded">
                            <div class="p-4">
                                <h1 class="display-6 mb-4">Cart <span class="fw-normal">Total</span></h1>
                                <div class="d-flex justify-content-between mb-4">
                                    <h5 class="mb-0 me-4">Subtotal:</h5>
                                    <p class="mb-0">${{subTotal}}</p>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <h5 class="mb-0 me-4">Shipping</h5>
                                    <div class="">
                                        <p class="mb-0">Flat rate: ${{shipping}}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="py-4 mb-4 border-top border-bottom d-flex justify-content-between">
                                {% if discount %}
                                    <h5 class="mb-0 ps-4 me-4">Total</h5>
                                    <p class="mb-0 pe-4"><del>${{originalTotal}}</del> ${{grandTotal}}</p>
                                {% else %}
                                <h5 class="mb-0 ps-4 me-4">Total</h5>
                                <p class="mb-0 pe-4">${{grandTotal}}</p>
                                {% endif %}
                            </div>
                            <a href="{% url "order:checkout" subTotal shipping %}" style="text-decoration:none">
                                <button class="btn border-secondary rounded-pill px-4 py-3 text-primary text-uppercase mb-4 ms-4" type="button">Proceed Checkout</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Cart Page End -->


{% endblock content %}