accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('profile',views.profile,name='profile'),
    path('login',views.login_view,name='login_view'),
    path('logout',views.logout_view,name='logout'),
    path('edit_profile',views.edit_profile,name='edit_profile'),
    path('reset_password',views.reset_password,name='reset_password'),
]

api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views as vs
from . import views

app_name='api'

router=DefaultRouter()
router.register('products',views.ProductViewsets)
router.register('categories',views.CategoryViewsets)
router.register('reviews',views.ReviewViewsets)
router.register('offers',views.OfferViewsets)
router.register('cart',views.CartViewsets)
router.register('coupon',views.CouponViewsets)
router.register('order',views.OrderViewsets)
router.register('order_products',views.OrderProductViewsets)
router.register('users',views.UserViewsets)

urlpatterns = [
    path('',include(router.urls)),
    path('api-token-auth/', vs.obtain_auth_token),
]

order/urls.py
from django.urls import path
from . import views

app_name='order'

urlpatterns = [
    path('',views.orders,name='orders'),
    path('checkout/<int:subTotal>/<int:shipping>',views.checkout,name='checkout'),
    path('cancel/<int:order_id>',views.cancel_order,name='cancel'),
    path('approve/<int:order_id>',views.approve_order,name='approve'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('shop/',include('shop.urls',namespace='shop')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('order/',include('order.urls',namespace='order')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('api/',include('api.urls',namespace='api')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

def profile_upload(instance,filename:str):
    extension = filename.split('.')[1]
    return f'accounts/{instance.user}.{extension}'

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=profile_upload)
    phone = models.CharField(max_length=15)

    class Meta:
        verbose_name = ("Profile")
        verbose_name_plural = ("Profiles")

    def __str__(self):
        return str(self.user)
    
    @receiver(post_save,sender=User)
    def created_user(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

accounts/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']	    
        
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','username','email']
        
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields  = '__all__'        
        exclude = 'user',

accounts/views.py
from django.shortcuts import render,redirect
from .forms import *
from order.models import Order
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout

# Create your views here.
def register(request):
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data['username']
            password=form.cleaned_data['password1']
            user=authenticate(username=username,password=password)
            login(request,user)
            return redirect("accounts:profile")
    context={
        'form':RegisterForm()
    }
    return render(request,"accounts/register.html",context)

def login_view(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        if username and password:
            user=authenticate(username=username,password=password)
            if user:
                login(request,user)
                return redirect('accounts:profile')
            else:
                return render(request,'error.html')
        else:
            return render(request,'error.html')
    return render(request,'accounts/login.html')

def profile(request,order=None):
    profile=Profile.objects.get(user=request.user)
    try:
        order=Order.objects.all().filter(user=request.user)
    except:
        pass
    context={
        'profile':profile,
        'order':order,
    }
    return render(request,'accounts/profile.html',context)

def logout_view(request):
    logout(request)
    return redirect("accounts:login_view")

def edit_profile(request):
    profile=Profile.objects.get(user=request.user)
    if request.method=="POST":
        uForm = UserForm(request.POST,instance=request.user)
        pForm= ProfileForm(request.POST,request.FILES,instance=profile)
        if uForm.is_valid() and pForm.is_valid():
            uForm.save()
            pForm.save()
            return redirect('accounts:profile')
        else:
            return render(request,'error.html')
    else:
        uForm=UserForm(instance=request.user)
        pForm=ProfileForm(instance=profile)
    context={
        'userForm':uForm,
        'profileForm':pForm,
    }
    return render(request,'accounts/edit_profile.html',context)

def reset_password(request):
    if request.method=='POST':
        user=request.user
        username=request.POST['username']
        password=request.POST['password']
        new_password=request.POST['new_password']
        user=authenticate(username=username,password=password)
        if user:
            user.set_password(new_password)
            user.save()
            login(request,user)
            return redirect('accounts:profile')
                
    return render(request,'accounts/reset_password.html')

templates/accounts/edit_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <title>Fruitables - Vegetable Website Template</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet"> 

        <!-- Icon Font Stylesheet -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="{% static "lib/lightbox/css/lightbox.min.css" %}" rel="stylesheet">
        <link href="{% static "lib/owlcarousel/assets/owl.carousel.min.css" %}" rel="stylesheet">


        <!-- Customized Bootstrap Stylesheet -->
        <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static "css/style.css" %}" rel="stylesheet">
    </head>

    <body style="margin-top:8%">

        {% include "includes/navbar.html" %}
        <div class="w-100 d-flex justify-content-center align-items-center">

            <form action="{% url "accounts:edit_profile" %}"  method="POST" id="#form" class="mt-5 p-xxl-5 card pt-4 px-5">
                {{userForm}}
                {{profileForm}}
                {% csrf_token %}
                <div class="mt-2 d-flex justify-content-center align-items-center">
                    <input type="submit" class="form-control border-0" style="width:400px">
                </div>
            </form>
        </div>

        {% include "includes/footer.html" %}
    <!-- Back to Top -->
    <a href="#" class="btn btn-primary border-3 border-primary rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>   

            
    <!-- JavaScript Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static "lib/easing/easing.min.js" %}"></script>
    <script src="{% static "lib/waypoints/waypoints.min.js" %}"></script>
    <script src="{% static "lib/lightbox/js/lightbox.min.js" %}"></script>
    <script src="{% static "lib/owlcarousel/owl.carousel.min.js" %}"></script>

    <!-- Template Javascript -->
    <script src="{% static "js/main.js" %}"></script>
    <script src="{% static "js/forms.js" %}"></script>
    </body>

</html>

templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <title>Fruitables - Vegetable Website Template</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet"> 

        <!-- Icon Font Stylesheet -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="{% static "lib/lightbox/css/lightbox.min.css" %}" rel="stylesheet">
        <link href="{% static "lib/owlcarousel/assets/owl.carousel.min.css" %}" rel="stylesheet">


        <!-- Customized Bootstrap Stylesheet -->
        <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static "css/style.css" %}" rel="stylesheet">
    </head>

    <body>

        {% include "includes/navbar.html" %}

        <div class="d-flex justify-content-center align-items-center w-100" style="height:600px;">
            
            <form action="{% url "accounts:login_view" %}" method="POST">
                {% csrf_token %}
                {% comment %} <h4 class="mb-5 fw-bold">Leave a Reply</h4> {% endcomment %}
                <div class="\">
                    <div class="w-100 pt-lg-5">
                        <div class="border-bottom rounded">
                            <input type="text" name="username" class="form-control border-0" placeholder="Your Username *">
                        </div>
                    </div>
                    <div class="w-100 pt-lg-5">
                        <div class="border-bottom rounded">
                            <input type="password" name="password" class="form-control border-0" placeholder="Your Password *" style="width:400px">
                        </div>
                    </div>
                    <div class="w-100 pt-lg-5">
                        <div class="border-bottom rounded">
                            <input type="submit" class="form-control border-0" title="Login" style="width:400px">
                        </div>
                    </div>
                </div>
            </form>
        </div>

        {% include "includes/footer.html" %}

templates/accounts/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <title>Fruitables - Vegetable Website Template</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet"> 

        <!-- Icon Font Stylesheet -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="{% static "lib/lightbox/css/lightbox.min.css" %}" rel="stylesheet">
        <link href="{% static "lib/owlcarousel/assets/owl.carousel.min.css" %}" rel="stylesheet">


        <!-- Customized Bootstrap Stylesheet -->
        <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static "css/style.css" %}" rel="stylesheet">
    </head>

    <body style="margin-top:15%">

        {% include "includes/navbar.html" %}
<div class="d-flex justify-content-center align-items-center w-100">
    <div class="bg-light rounded w-50">
        
        <div class="p-4 d-flex align-items-center justify-content-between">
            {% if profile.image %}
            <div class="">
                <img src="{{profile.image.url}}" class="img-fluid me-5 rounded-circle" style="width: 80px; height: 80px;" alt="">
            </div>
            {% endif %}
            <h1 class="display-6">{{profile}}</h1>
            
            <a href="{% url "order:orders" %}" class="my-auto " data-bs-toggle="tooltip" data-bs-placement="top">
                <i class="fas fa-receipt fa-3x ms-3"></i>
            </a>
        </div>
        <div class="py-4 mb-4 border-top d-flex justify-content-between">
            <h5 class="mb-0 ps-4 me-4">Email</h5>
            <p class="mb-0 pe-4">{{profile.user.email}}</p>
        </div>
        <div class="py-4 mb-4 border-top d-flex justify-content-between">
            <h5 class="mb-0 ps-4 me-4">Phone Number</h5>
            <p class="mb-0 pe-4">{{profile.phone}}</p>
        </div>
        
        <a href="{% url "accounts:edit_profile" %}">
            <button class="btn border-secondary rounded-pill px-4 py-3 text-primary text-uppercase mb-4 ms-4" type="button">Edit Profile</button>
        </a>
        <a href="{% url "accounts:reset_password" %}">
            <button class="btn border-secondary rounded-pill px-4 py-3 text-primary text-uppercase mb-4 ms-4" type="button">Reset Password</button>
        </a>
    </div>
</div>

{% include "includes/footer.html" %}

    <!-- Back to Top -->
    <a href="#" class="btn btn-primary border-3 border-primary rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>   

        
    <!-- JavaScript Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static "lib/easing/easing.min.js" %}"></script>
    <script src="{% static "lib/waypoints/waypoints.min.js" %}"></script>
    <script src="{% static "lib/lightbox/js/lightbox.min.js" %}"></script>
    <script src="{% static "lib/owlcarousel/owl.carousel.min.js" %}"></script>

    <!-- Template Javascript -->
    <script src="{% static "js/main.js" %}"></script>
    <script src="{% static "js/forms.js" %}"></script>
    </body>

</html>

templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <title>Fruitables - Vegetable Website Template</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet"> 

        <!-- Icon Font Stylesheet -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="{% static "lib/lightbox/css/lightbox.min.css" %}" rel="stylesheet">
        <link href="{% static "lib/owlcarousel/assets/owl.carousel.min.css" %}" rel="stylesheet">


        <!-- Customized Bootstrap Stylesheet -->
        <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static "css/style.css" %}" rel="stylesheet">
    </head>

    <body style="margin-top:9%">

        {% include "includes/navbar.html" %}

        <div class="my-lg-5 p-xxl-5 w-100">
            <div class="d-flex justify-content-center align-items-center p-2 bg-">
                <form action="{% url "accounts:register" %}" method="POST" id="#form" class="my-5 p-xxl-5 card p-5">
                    {{form}}
                    {% csrf_token %}
                    <div class=" mt-2 d-flex justify-content-center align-items-center">
                        <input type="submit" class="form-control border-0" value="Register" style="width:400px">
                    </div>
                </form>
            </div>
        </div>
        
        {% include "includes/footer.html" %}

    <!-- Back to Top -->
    <a href="#" class="btn btn-primary border-3 border-primary rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>   

        
    <!-- JavaScript Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static "lib/easing/easing.min.js" %}"></script>
    <script src="{% static "lib/waypoints/waypoints.min.js" %}"></script>
    <script src="{% static "lib/lightbox/js/lightbox.min.js" %}"></script>
    <script src="{% static "lib/owlcarousel/owl.carousel.min.js" %}"></script>

    <!-- Template Javascript -->
    <script src="{% static "js/main.js" %}"></script>
    <script src="{% static "js/forms.js" %}"></script>
    </body>

</html>

templates/accounts/reset_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <title>Fruitables - Vegetable Website Template</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet"> 

        <!-- Icon Font Stylesheet -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="{% static "lib/lightbox/css/lightbox.min.css" %}" rel="stylesheet">
        <link href="{% static "lib/owlcarousel/assets/owl.carousel.min.css" %}" rel="stylesheet">


        <!-- Customized Bootstrap Stylesheet -->
        <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static "css/style.css" %}" rel="stylesheet">
    </head>

    <body>

        {% include "includes/navbar.html" %}

        <div class="d-flex justify-content-center align-items-center w-100" style="height:600px;">
            
            <form action="{% url "accounts:reset_password" %}" method="POST">
                {% csrf_token %}
                {% comment %} <h4 class="mb-5 fw-bold">Leave a Reply</h4> {% endcomment %}
                <div class="\">
                    <div class="w-100 pt-lg-5">
                        <div class="border-bottom rounded">
                            <input type="text" name="username" class="form-control border-0" placeholder="Your Username *">
                        </div>
                    </div>
                    <div class="w-100 pt-lg-5">
                        <div class="border-bottom rounded">
                            <input type="password" name="password" class="form-control border-0" placeholder="Your Password *" style="width:400px">
                        </div>
                    </div>
                    <div class="w-100 pt-lg-5">
                        <div class="border-bottom rounded">
                            <input type="password" name="new_password" class="form-control border-0" placeholder="New Password *" style="width:400px">
                        </div>
                    </div>
                    <div class="w-100 pt-lg-5">
                        <div class="border-bottom rounded">
                            <input type="submit" class="form-control border-0" title="Login" style="width:400px">
                        </div>
                    </div>
                </div>
            </form>
        </div>

        {% include "includes/footer.html" %}