api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views as vs
from . import views

app_name='api'

router=DefaultRouter()
router.register('products',views.ProductViewsets)
router.register('categories',views.CategoryViewsets)
router.register('reviews',views.ReviewViewsets)
router.register('offers',views.OfferViewsets)
router.register('cart',views.CartViewsets)
router.register('coupon',views.CouponViewsets)
router.register('order',views.OrderViewsets)
router.register('order_products',views.OrderProductViewsets)
router.register('users',views.UserViewsets)

urlpatterns = [
    path('',include(router.urls)),
    path('api-token-auth/', vs.obtain_auth_token),
]

cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('',views.cart,name='cart'),
    path('remove_cart/<int:item_id>',views.remove_cart,name='remove_cart'),
    path('add_cart/<int:product_id>',views.add_cart,name='add_cart'),
    path('add_item/<int:item_id>',views.add_item,name='add_item'),
    path('remove_item/<int:item_id>',views.remove_item,name='remove_item'),
]

order/urls.py
from django.urls import path
from . import views

app_name='order'

urlpatterns = [
    path('',views.orders,name='orders'),
    path('checkout/<int:subTotal>/<int:shipping>',views.checkout,name='checkout'),
    path('cancel/<int:order_id>',views.cancel_order,name='cancel'),
    path('approve/<int:order_id>',views.approve_order,name='approve'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('shop/',include('shop.urls',namespace='shop')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('order/',include('order.urls',namespace='order')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('api/',include('api.urls',namespace='api')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns = [
    path('',views.shop,name='shop'),
    path('price',views.shop_price,name='shop_price'),
    path('cats/<str:cat_name>/',views.shop_cats,name='shop_cats'),
    path('product_details/<str:product_name>',views.product_details,name='product_details'),
    path('search',views.search,name='search'),
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import Product

# Create your models here.
class Cart(models.Model):
    user=models.ForeignKey(User, verbose_name=("User"), on_delete=models.CASCADE,null=True)
    product=models.ForeignKey(Product, verbose_name=("Product"), on_delete=models.CASCADE)
    quantity=models.IntegerField(verbose_name=("Quantity"))
    price=models.IntegerField(verbose_name=("Price"),null=True,blank=True,)
    total=models.IntegerField(verbose_name=("Total"),null=True,blank=True)
    
    class Meta:
        verbose_name = ("Cart")
        verbose_name_plural = ("Carts")
        
    def save(self,*args,**kwargs):
        if self.quantity > self.product.stock:
            self.quantity=self.product.stock
        if self.product.offer_price:
            self.price=self.product.offer_price
        else:
            self.price=self.product.price
        self.total=self.quantity*self.price
        super(Cart,self).save(*args, **kwargs)

    def __str__(self):
        return str(self.product)

class Coupon(models.Model):
    coupon=models.CharField(verbose_name=("Coupon"),max_length=50)
    ratio=models.IntegerField(verbose_name=("Ratio"))
    created_at=models.DateField(verbose_name=("Created at"), auto_now=True)
    expiry_date=models.DateField(verbose_name=("Expires at"),null=True)
    is_available=models.BooleanField(verbose_name=("Is Available"),default=True)

    class Meta:
        verbose_name = ("Coupon")
        verbose_name_plural = ("Coupons")
        
    def save(self,*args,**kwargs):
        self.coupon=str(self.coupon).upper()
        super(Coupon,self).save(*args, **kwargs)

    def __str__(self):
        return str(self.coupon).upper()

shop/models.py
from django.db import models
from django.contrib.auth.models import User

def image_upload(instance,filename:str):
    extension=filename.split('.')[1]
    return f"products/{instance.name}.{extension}"

# Create your models here.
class Category(models.Model):
    title = models.CharField(verbose_name='Category Name' ,unique=True ,max_length=50)
    createdOn = models.DateField(verbose_name='Created On' ,auto_now=True)
    isAvailable = models.BooleanField(default=True,verbose_name=('Is Available'))
    
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
    
    def __str__(self) -> str:
        return str(self.title).capitalize()
    
class Offer(models.Model):
    title=models.CharField(verbose_name=("Title"),max_length=50)
    ratio=models.IntegerField(verbose_name=("Ratio"))
    created_at=models.DateField(verbose_name=("Created at"), auto_now=True)
    expiry_date=models.DateField(verbose_name=("Expires at"),null=True)
    is_available=models.BooleanField(verbose_name=("Is Available"),default=True)
    
    def __str__(self):
        return str(self.title)

class Product(models.Model):
    name = models.CharField(verbose_name='Product Name',unique=True ,max_length=50)
    description = models.TextField(verbose_name='Description' ,max_length=200)
    price = models.IntegerField(verbose_name='Price')
    stock = models.IntegerField(verbose_name='Stock')
    addedOn = models.DateField(verbose_name='Addition Date' ,auto_now=True)
    images = models.ImageField(verbose_name='Image' ,upload_to=image_upload,null=True)
    category = models.ForeignKey(Category,verbose_name='Category' , on_delete=models.CASCADE)
    offer = models.ForeignKey(Offer,verbose_name="Offer",on_delete=models.PROTECT,null=True,blank=True)
    offer_price = models.IntegerField(verbose_name=("Offer Price"),null=True,blank=True)
    
    def save(self,*args, **kwargs):
        if self.offer:
            self.offer_price=self.price-((self.offer.ratio/100)*self.price)
        if self.stock <0:
            self.stock=0
        super(Product,self).save(*args, **kwargs)
    
    def __str__(self) -> str:
        return str(self.name)

class Reviews(models.Model):
    user=models.ForeignKey(User, verbose_name=("User"), on_delete=models.CASCADE)
    product=models.ForeignKey(Product, verbose_name=("Product"), on_delete=models.CASCADE)
    review=models.TextField(verbose_name=("Review"))
    date_created=models.DateField(verbose_name=("Creation date"), auto_now=True)

    class Meta:
        unique_together=(('user','product'),)
        verbose_name = ("Reviews")
        verbose_name_plural = ("Reviews")

    def __str__(self):
        return f"{self.user} / {self.product}"

cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .models import *

# Create your views here.
@login_required(login_url='accounts:login_view')
def cart(request,subTotal=0,shipping=50,grandTotal=0,discount=0,originalTotal=0):
    try:
        try:
            cartItem=Cart.objects.all().filter(user=request.user)
            for item in cartItem:
                subTotal+=item.total
        except:
            cartItem=None
        if request.method=='POST':
            
            discount=request.POST['coupon']
            if discount:
                try:
                    coupon=Coupon.objects.get(coupon=str(discount))
                    grandTotal=subTotal+shipping
                    originalTotal=grandTotal
                    discount=grandTotal*(coupon.ratio/100)
                    grandTotal=int(grandTotal-discount)
                except:
                    pass
        else:
            shipping=50
            grandTotal=subTotal+shipping
    except:
        pass
    context={
        'subTotal':subTotal,
        'grandTotal':grandTotal,
        'shipping':shipping,
        'discount':discount,
        'originalTotal':originalTotal,
        'cartItem':cartItem,
    }
    
    return render(request,'cart/cart.html',context)

def remove_cart(request,item_id):
    
    cartItem=Cart.objects.get(id=item_id)
    cartItem.delete()
    
    return redirect('cart:cart')

def add_item(request,item_id):
    cartItem=Cart.objects.get(id=item_id)
    cartItem.quantity+=1
    cartItem.save()
    
    return redirect('cart:cart')

def remove_item(request,item_id):
    cartItem=Cart.objects.get(id=item_id)
    if cartItem.quantity>1:
        cartItem.quantity-=1
        cartItem.save()
    else:
        cartItem.delete()
    return redirect('cart:cart')

@login_required(login_url='accounts:login_view')
def add_cart(request,product_id,cartItem=None):
    product=Product.objects.get(id=product_id)
    
    try:
        cartItem=Cart.objects.get(user=request.user,product=product)
    except:pass
    if cartItem:
        cartItem.quantity+=1
        cartItem.save()
    else:
        if request.method=='POST':
            amount=int(request.POST["quantity"])
            if amount:
                cartItem=Cart(user=request.user,product=product,quantity=amount)
                cartItem.save()
        else:
            return redirect("cart:product_details")
    return redirect("cart:cart")

shop/views.py
from django.shortcuts import render,redirect
from .models import *
from django.core.paginator import Paginator
from django.db.models import Q

# Create your views here.
def shop(request):
    cat=Category.objects.all()
    product=Product.objects.all().filter(stock__gt=0).order_by('-offer')
    products=Product.objects.all().order_by('-offer')
    p = Paginator(product, 6)
    page_number=request.GET.get("page")
    page_object=p.get_page(page_number)
    context={
        'category':cat,
        'products':products,
        'product':page_object,
        'number':page_number,
    }
    return render(request,'shop/shop.html',context)

def shop_price(request):
    if request.method=="POST":
        prices=request.POST['amount']
        cat=Category.objects.all()
        product=Product.objects.all().filter(price__lte=prices).order_by('-price')
        products=Product.objects.all().order_by('-offer')
        context={
            'category':cat,
            'products':products,
            'product':product,
        }
        return render(request,'shop/shop.html',context)
    
    return redirect('shop:shop')

def shop_cats(request,cat_name=None,catObj=None,product=None):
    products=Product.objects.all().order_by('-offer')
    try:
        catObj=Category.objects.get(title=cat_name)
        cat=Category.objects.all()
        product=Product.objects.all().filter(category=catObj)
    except:
        cat=Category.objects.all()
        product=Product.objects.all()
    p = Paginator(product, 6)
    page_number=request.GET.get("page")
    page_object=p.get_page(page_number)
    context={
        'cat_obj':catObj,
        'category':cat,
        'products':products,
        'product':page_object,
        'number':page_number
    }
    return render(request,'shop/shop.html',context)

def search(request,keyword=None,category=None):
    product=Product.objects.all().order_by('-offer')
    if request.method == "POST":
        keyword=request.POST["keyword"]
        if keyword:
            cat=Category.objects.all()
            try:    
                try:
                    category=Category.objects.get(Q(title__icontains=keyword))
                    products=Product.objects.order_by('-addedOn').filter(Q(description__icontains=keyword) | Q(name__icontains=keyword) | Q(category=category))
                except:
                    products=Product.objects.order_by('-addedOn').filter(Q(description__icontains=keyword) | Q(name__icontains=keyword) )
                p = Paginator(products, 6)
                page_number=request.GET.get("page")
                page_object=p.get_page(page_number)
                context={
                    'category':cat,
                    'product':page_object,
                    'number':page_number,
                    'products':product,
                }
                return render(request,'shop/shop.html',context)
            except:pass
        
    return redirect("shop:shop")
        
    

def product_details(request,product_name,reviews=None):
    product=Product.objects.get(name=product_name)
    products=Product.objects.all()
    
    cat=Category.objects.all()
    try:
        reviews=Reviews.objects.all().filter(product=product)
    except:pass
    if request.method=='POST':
        rev=request.POST['review']
        try:
            revObj=Reviews.objects.get(user=request.user,product=product)
            revObj.review=rev
            revObj.save()
        except:
            review=Reviews(user=request.user,product=product,review=rev)
            review.save()
            
    context={
        'category':cat,
        'product':product,
        'products':products,
        'reviews':reviews
    }
    return render(request,'shop/product_details.html',context)

templates/shop/cart.html
{% extends "base.html" %}

{% block content %}

        <!-- Cart Page Start -->
        <div class="container-fluid py-5 mt-5">
            <div class="container py-5">
                <div class="table-responsive">
                    {% if cartItem %}
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">Products</th>
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total</th>
                            <th scope="col">Handle</th>
                          </tr>
                        </thead>
                        
                        {% if cartItem %}
                        {% for item in cartItem %}
                        <tbody>
                            <tr>
                                <th scope="row">
                                    <div class="d-flex align-items-center">
                                        <img src="{{item.product.images.url}}" class="img-fluid me-5 rounded-circle" style="width: 80px; height: 80px;" alt="">
                                    </div>
                                </th>
                                <td>
                                    <p class="mb-0 mt-4">{{item}}</p>
                                </td>
                                <td>
                                    <p class="mb-0 mt-4">{{item.price}} $</p>
                                </td>
                                <td>
                                    <div class="input-group quantity mt-4" style="width: 100px;">
                                        <div class="input-group-btn">
                                            <a href="{% url "shop:remove_item" item.id %}">
                                                <button class="btn btn-sm btn-minus rounded-circle bg-light border" >
                                                    <i class="fa fa-minus"></i>
                                                </button>
                                            </a>
                                        </div>
                                        <div class="form-control form-control-sm text-center border-0 bg-transparent">{{item.quantity}}</div>
                                        <div class="input-group-btn">
                                            <a href="{% url "shop:add_item" item.id %}">
                                                <button class="btn btn-sm btn-minus rounded-circle bg-light border" >
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            </a>
                                        </div>
                                        
                                    </div>
                                </td>
                                <td>
                                    <p class="mb-0 mt-4">{{item.total}} $</p>
                                </td>
                                <td>
                                    <a href="{% url "shop:remove_cart" item.id %}">
                                        <button class="btn btn-md rounded-circle bg-light border mt-4" >
                                            <i class="fa fa-times text-danger"></i>
                                        </button>
                                    </a>
                                </td>
                            
                            </tr>
                            {% endfor %}
                        {% endif %}
                            {% else %}
                            <div class="py-4 mb-4 border-top border-bottom d-flex justify-content-center">
                                <h2 class="mb-0 ps-4 me-4">No Items</h2>
                                <a href="{% url "shop:shop" %}">
                                    <button class="btn btn-md  bg-light border" >
                                        Add Item
                                    </button>
                                </a>
                            </div>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
                <div class="mt-5">
                    <form action="{% url "shop:cart" %}" method="POST">
                        {% csrf_token %}
                        <input type="text" class="border-0 border-bottom rounded me-5 py-3 mb-4" placeholder="Coupon Code" name='coupon'>
                        <input class="btn border-secondary rounded-pill px-4 py-3 text-primary" type="submit" value="Apply Coupon">
                    </form>
                </div>
                <div class="row g-4 justify-content-end">
                    <div class="col-8"></div>
                    <div class="col-sm-8 col-md-7 col-lg-6 col-xl-4">
                        <div class="bg-light rounded">
                            <div class="p-4">
                                <h1 class="display-6 mb-4">Cart <span class="fw-normal">Total</span></h1>
                                <div class="d-flex justify-content-between mb-4">
                                    <h5 class="mb-0 me-4">Subtotal:</h5>
                                    <p class="mb-0">${{subTotal}}</p>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <h5 class="mb-0 me-4">Shipping</h5>
                                    <div class="">
                                        <p class="mb-0">Flat rate: ${{shipping}}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="py-4 mb-4 border-top border-bottom d-flex justify-content-between">
                                {% if discount %}
                                    <h5 class="mb-0 ps-4 me-4">Total</h5>
                                    <p class="mb-0 pe-4"><del>${{originalTotal}}</del> ${{grandTotal}}</p>
                                {% else %}
                                <h5 class="mb-0 ps-4 me-4">Total</h5>
                                <p class="mb-0 pe-4">${{grandTotal}}</p>
                                {% endif %}
                            </div>
                            <a href="{% url "order:checkout" subTotal shipping %}" style="text-decoration:none">
                                <button class="btn border-secondary rounded-pill px-4 py-3 text-primary text-uppercase mb-4 ms-4" type="button">Proceed Checkout</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Cart Page End -->


{% endblock content %}

templates/shop/shop.html
{% extends "base.html" %}

{% block content %}
<!-- Single Page Header start -->
<div class="container-fluid page-header py-5">
    <h1 class="text-center text-white display-6">Shop</h1>
    <ol class="breadcrumb justify-content-center mb-0">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item"><a href="#">Pages</a></li>
        <li class="breadcrumb-item active text-white">Shop</li>
    </ol>
</div>
<!-- Single Page Header End -->


<!-- Fruits Shop Start-->
<div class="container-fluid fruite py-5">
    <div class="container py-5">
        <h1 class="mb-4">Fresh fruits shop</h1>
        <div class="row g-4">
            <div class="col-lg-12">
                <div class="row g-4">
                    <div class="col-xl-3">
                        <div class="input-group w-100 mx-auto d-flex">
                            <form method="POST" action="{% url "shop:search" %}">
                                {% csrf_token %}
                                <input type="search" class="form-control p-3" placeholder="keywords" name="keyword" aria-describedby="search-icon-1">
                            </form>
                            <span id="search-icon-1" class="input-group-text p-3"><i class="fa fa-search"></i></span>
                        </div>
                    </div>
                    <div class="col-6"></div>
                    <div class="col-xl-3">
                        <div class="bg-light ps-3 py-3 rounded d-flex justify-content-between mb-4">
                            <label for="fruits">Default Sorting:</label>
                            <select id="fruits" name="fruitlist" class="border-0 form-select-sm bg-light me-3" form="fruitform">
                                <option value="volvo">Nothing</option>
                                <option value="saab">Popularity</option>
                                <option value="opel">Organic</option>
                                <option value="audi">Fantastic</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row g-4">
                    <div class="col-lg-3">
                        <div class="row g-4">
                            <div class="col-lg-12">
                                <div class="mb-3">
                                    <h4>Categories</h4>
                                    <ul class="list-unstyled fruite-categorie">
                                        {% for cat in category %}
                                        <li>
                                            <div class="d-flex justify-content-between fruite-name">
                                                <a href="{% url "shop:shop_cats" cat.title %}"><i class="fas fa-apple-alt me-2"></i>{{cat}}</a>
                                            </div>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="mb-3">
                                    <form method="POST" action="{% url "shop:shop_price" %}">
                                        {% csrf_token %}
                                        <h4 class="mb-2">Price</h4>
                                        <input type="range" class="form-range w-100" id="rangeInput" name="rangeInput" min="0" max="500" value="0" oninput="amount.value=rangeInput.value">
                                        <div class="d-flex justify-content-between">
                                            <input class="border-0" id="amount" name="amount" min-velue="0" max-value="500" value="0" for="rangeInput">
                                            <input class="btn border border-secondary text-primary rounded-pill px-3 py-2" value="Apply" type="submit">
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <h4 class="mb-4">Featured products</h4>
                                {% for pro in products %}
                                {% if pro.offer %}
                                <a href="{% url "shop:product_details" pro.name %}">
                                    <div class="d-flex align-items-center justify-content-start">
                                        <div class="rounded me-4" style="width: 100px; height: 100px;">
                                            <img src="{{pro.images.url}}" class="img-fluid rounded" alt="Image">
                                        </div>
                                        <div>
                                            <h6 class="mb-2">{{pro}}</h6>
                                            <div class="d-flex mb-2">
                                                <h5 class="fw-bold me-2">{{pro.offer_price}} $</h5>
                                                <h5 class="text-danger text-decoration-line-through">{{pro.price}}$</h5>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                                {% endif %}
                                {% endfor %}
                            </div>
                            
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <div class="row g-4 justify-content-center">
                            {% if product %}
                            {% for pro in product %}
                            
                            <div class="col-md-6 col-lg-6 col-xl-4">
                                <div class="rounded position-relative fruite-item">
                                    {% if pro.images %}
                                    <div class="fruite-img">
                                        <img src={{pro.images.url}} class="img-fluid w-100 rounded-top" alt="">
                                    </div>
                                    {% endif %}
                                    <div class="text-white bg-secondary px-3 py-1 rounded position-absolute" style="top: 10px; left: 10px;">{{pro.category}}</div>
                                    <div class="p-4 border border-secondary border-top-0 rounded-bottom">
                                        <h4>{{pro}}</h4>
                                        <p>{{pro.description}}</p>
                                        <div class="d-flex justify-content-between flex-lg-wrap">
                                            {% if pro.offer_price %}
                                            <p class="text-dark fs-5 fw-bold mb-0"> <del style="color:red">${{pro.price}} / kg</del></p>
                                            <p class="text-dark fs-5 fw-bold mb-0">${{pro.offer_price}} / kg</p>
                                            {% else %}

                                            <p class="text-dark fs-5 fw-bold mb-0">${{pro.price}} / kg</p>
                                            {% endif %}
                                            {% if pro.stock %}
                                            <a href="{% url "shop:product_details" pro.name %}" class="btn border border-secondary rounded-pill px-3 text-primary"><i class="fa fa-shopping-bag me-2 text-primary"></i> Add to cart</a>
                                            {% else %}
                                            <div class="p-4 d-flex justify-content-center">
                                                <p>Ot of stock</p>
                                            </div>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            {% else %}
                            <div class="p-4 d-flex justify-content-center">
                                <h4>No Products</h4>
                            </div>
                            {% endif %}
                            {% if product.has_other_pages %}
                            <div class="col-12">
                                <div class="pagination d-flex justify-content-center mt-5">
                                    {% if product.has_previous %}
                                    <a href="?page={{products.previous_page_number}}" class="rounded">&laquo;</a>
                                    {% endif %}
                                    {% comment %} <a href="#" class="active rounded">1</a> {% endcomment %}
                                    {% for i in product.paginator.page_range %}
                                    {% if i == number %}
                                    <a href="?page={{i}}" class="active rounded">{{i}}</a>
                                    {% else %}
                                    <a href="?page={{i}}" class="rounded">{{i}}</a>
                                    {% endif %}
                                    {% endfor %}
                                    {% if product.has_next %}
                                    <a href="?page={{product.next_page_number}}" class="rounded">&raquo;</a>
                                    {% endif %}
                                </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fruits Shop End-->

{% endblock content %}